/*
    Here you can change the texts of the 
*/
module.exports = {
    Songs: [
        "Stereo Madness",
        "Back On Track",
        "Polargeist",
        "Dry Out",
        "Base After Base",
        "Cant Let Go",
        "Jumper",
        "Time Machine",
        "Cycles",
        "xStep",
        "Clutterfunk",
        "Theory of Everything",
        "Electroman Adventures",
        "Clubstep",
        "Electrodynamix",
        "Hexagon Force",
        "Blast Processing",
        "Theory of Everything 2",
        "Geometrical Dominator",
        "Deadlocked",
        "Fingerdash",
        // "Dash", // 2.2 Song
        // "Explorers", // 2.2 Song
        "The Seven Seas",
        "Viking Arena",
        "Airborne Robots",
        "Secret",
        "Payload",
        "Beast Mode",
        "Machina",
        "Years",
        "Frontlines",
        "Space Pirates",
        "Striker",
        "Embers",
        "Round 1",
        "Monster Dance Off",
        "Press Start",
        "Nock Em",
        "Power Trip",
    ],
    Authors: [
        "ForeverBound",
        "DJVI",
        "Step",
        "DJVI",
        "DJVI",
        "DJVI",
        "Waterflame",
        "Waterflame",
        "DJVI",
        "DJVI",
        "Waterflame",
        "DJ-Nate",
        "Waterflame",
        "DJ-Nate",
        "DJ-Nate",
        "Waterflame",
        "Waterflame",
        "DJ-Nate",
        "Waterflame",
        "F-777",
        "MDK",
        // "MDK", // 2.2 Song
        // "Hinkik", // 2.2 Song
        "F-777",
        "F-777",
        "F-777",
        "RobTopGames",
        "Dex Arson",
        "Dex Arson",
        "Dex Arson",
        "Dex Arson",
        "Dex Arson",
        "Waterflame",
        "Waterflame",
        "Dex Arson",
        "Dex Arson",
        "F-777",
        "MDK",
        "Bossfight",
        "Boom Kitty",
    ],
    DefaultSong: "Unknown",
    DefaultAuthor: "DJVI",
}